from sqlalchemy import ForeignKey, create_engine, Column, String, Integer, Float, JSON, Text, TIMESTAMP, func, MetaData, PrimaryKeyConstraint
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base
from pgvector.sqlalchemy import Vector        # sqlalchemy的vector支持需要下载源码并手动编译

Base = declarative_base()
metadata = MetaData()

# ------------------ 以下部分数据库设计为了实现股票与指数之间的多对多设计 ------------------ # 
# 股票基础信息表
class StockInfo(Base):
    __tablename__ = 'stock_info'
    symbol = Column(String(20), primary_key=True)
    name = Column(String(50))
    area = Column(String(50), nullable=True)                   
    update_time = Column(TIMESTAMP)
    
    components = relationship("SectorComponent", back_populates="stock", cascade="all, delete-orphan")
    vectors = relationship("VectorRecord", back_populates="stock", cascade="all, delete-orphan")

# 指数 / 板块基础信息
class SectorInfo(Base):
    __tablename__ = 'sector_info'
    name = Column(String(30), primary_key=True)
    code = Column(String(30), nullable=True)
    update_time = Column(TIMESTAMP)

    components = relationship("SectorComponent", back_populates="sector", cascade="all, delete-orphan")
    
# 用于记录股票与指数之间的多对多关系(即保存了所有的 股票代码 与 指数+行业 之间的对应关系)
class SectorComponent(Base):
    __tablename__ = 'sector_components'
    # 定义字段
    sector_name = Column(String, ForeignKey('sector_info.name', ondelete='CASCADE'), primary_key=True)
    stock_code = Column(String, ForeignKey('stock_info.symbol', ondelete='CASCADE'), primary_key=True)

    sector = relationship("SectorInfo", back_populates="components")
    stock = relationship("StockInfo", back_populates="components")
    
# -------------------------- 向量主表，其对应了股票的向量数据库，用于大模型记忆与检索 ------------------------- # 
class VectorRecord(Base):
    __tablename__ = 'vector_record'
    id = Column(Integer, primary_key=True, autoincrement=True)
    stock_symbol = Column(String(20), ForeignKey('stock_info.symbol'), nullable=False)
    embedding = Column(Vector)
    content = Column(Text)
    params = Column(JSON)
    created_at = Column(TIMESTAMP, server_default=func.now())

    stock = relationship("StockInfo", back_populates="vectors")

# 每日板块指数信息(东方财富自定义板块 + 大盘指数)
class RealtimeSector(Base):
    __tablename__ = 'sector'
    name = Column(String(50), primary_key=True)
    code = Column(String(30), nullable=True)
    change_percent = Column(Float)
    price = Column(Float)  
    volume = Column(Float)
    update_time = Column(TIMESTAMP)

# 每日大盘中各股信息
class RealtimeShare(Base):
    __tablename__ = 'ashare'
    symbol = Column(String(20))
    name = Column(String(50))
    price = Column(Float)
    change_percent = Column(Float)
    change_amount = Column(Float)
    volume = Column(Float)
    amount = Column(Float)
    amplitude = Column(Float)
    high = Column(Float)
    low = Column(Float)
    open = Column(Float)
    close = Column(Float)
    previous_close = Column(Float)
    volume_ratio = Column(Float)
    turnover = Column(Float)
    pe_dynamic = Column(Float)
    pb_ratio = Column(Float)
    total_value = Column(Float)
    circulating_value = Column(Float)
    speed = Column(Float)
    change_5min = Column(Float)
    change_60d = Column(Float)
    change_ytd = Column(Float)
    update_time = Column(TIMESTAMP)

    # 定义复合主键
    __table_args__ = (
        PrimaryKeyConstraint('symbol', 'update_time', name='realtime_quote_pk'),
    )
    
# 每日新闻摘要记录
class RealtimeNews(Base):
    __tablename__ = 'news'
    id = Column(Integer, primary_key=True, autoincrement=True)
    abstract = Column(String(50))
    content = Column(String(100), nullable=True)
    main_body = Column(String(100), nullable=True)
    update_time = Column(TIMESTAMP)
    

class StockNews(Base):
    __tablename__ = 'stock_news'

    symbol = Column(String(10))
    keyword = Column(String(50))
    title = Column(String(255))
    content = Column(Text)
    source = Column(String(100))
    url = Column(String(255))
    timestamp = Column(TIMESTAMP)
    
    # 定义复合主键
    __table_args__ = (
        PrimaryKeyConstraint('symbol', 'timestamp', name='stock_news_pk'),
    )


# SECURITY_CODE(股票代码)与REPORT_DATE为主键
# 以下列明为大写，则在查询时需要用双引号将键值框起来（表明其味大写字符串）
class FinanceStatement(Base):
    __tablename__ = 'finance_statements'

    REPORT_DATE = Column(TIMESTAMP)        
    SECURITY_CODE = Column(String(20))
    ORG_CODE = Column(String(20))
    ORG_TYPE = Column(String(20))
    REPORT_TYPE = Column(String(20))
    MONETARYFUNDS = Column(Float)
    TRADE_FINASSET_NOTFVTPL = Column(Float)
    DERIVE_FINASSET = Column(Float)
    NOTE_ACCOUNTS_RECE = Column(Float)
    ACCOUNTS_RECE = Column(Float)
    NOTE_RECE = Column(Float)
    FINANCE_RECE = Column(Float)
    PREPAYMENT = Column(Float)
    TOTAL_OTHER_RECE = Column(Float)
    INTEREST_RECE = Column(Float)
    INVENTORY = Column(Float)
    CONTRACT_ASSET = Column(Float)
    AVAILABLE_SALE_FINASSET = Column(Float)
    NONCURRENT_ASSET_1YEAR = Column(Float)
    OTHER_CURRENT_ASSET = Column(Float)
    CURRENT_ASSET_OTHER = Column(Float)
    TOTAL_CURRENT_ASSETS = Column(Float)
    CREDITOR_INVEST = Column(Float)
    LONG_RECE = Column(Float)
    LONG_EQUITY_INVEST = Column(Float)
    OTHER_EQUITY_INVEST = Column(Float)
    OTHER_NONCURRENT_FINASSET = Column(Float)
    INVEST_REALESTATE = Column(Float)
    FIXED_ASSET = Column(Float)
    CIP = Column(Float)
    USERIGHT_ASSET = Column(Float)
    OIL_GAS_ASSET = Column(Float)
    INTANGIBLE_ASSET = Column(Float)
    DEVELOP_EXPENSE = Column(Float)
    LONG_PREPAID_EXPENSE = Column(Float)
    GOODWILL = Column(Float)
    DEFER_TAX_ASSET = Column(Float)
    OTHER_NONCURRENT_ASSET = Column(Float)
    OTHER_NONCURRENT_FINASSET = Column(Float)
    NONCURRENT_ASSET_OTHER = Column(Float)
    TOTAL_NONCURRENT_ASSETS = Column(Float)
    TOTAL_ASSETS = Column(Float)
    FVTPL_FINLIAB = Column(Float)
    SHORT_LOAN = Column(Float)
    DERIVE_FINLIAB = Column(Float)
    ACCOUNTS_PAYABLE = Column(Float)
    NOTE_ACCOUNTS_PAYABLE = Column(Float)
    ACCOUNTS_PAYABLE = Column(Float)
    NOTE_PAYABLE = Column(Float)
    DIVIDEND_PAYABLE = Column(Float)
    ADVANCE_RECEIVABLES = Column(Float)
    CONTRACT_LIAB = Column(Float)
    STAFF_SALARY_PAYABLE = Column(Float)
    TAX_PAYABLE = Column(Float)
    TOTAL_OTHER_PAYABLE = Column(Float)
    INTEREST_PAYABLE = Column(Float)
    PREDICT_CURRENT_LIAB = Column(Float)
    SHORT_BOND_PAYABLE = Column(Float)
    OTHER_CURRENT_LIAB = Column(Float)
    NONCURRENT_LIAB_1YEAR = Column(Float)
    CURRENT_LIAB_OTHER = Column(Float)
    TOTAL_CURRENT_LIAB = Column(Float)
    LONG_LOAN = Column(Float)
    BOND_PAYABLE = Column(Float)
    LEASE_LIAB = Column(Float)
    LONG_PAYABLE = Column(Float)
    LONG_STAFFSALARY_PAYABLE = Column(Float)
    PREDICT_CURRENT_LIAB = Column(Float)
    DEFER_INCOME = Column(Float)
    DEFER_TAX_LIAB = Column(Float)
    OTHER_NONCURRENT_LIAB = Column(Float)
    NONCURRENT_LIAB_OTHER = Column(Float)
    TOTAL_NONCURRENT_LIAB = Column(Float)
    TOTAL_LIABILITIES = Column(Float)
    SHARE_CAPITAL = Column(Float)
    CAPITAL_RESERVE = Column(Float)
    TREASURY_SHARES = Column(Float)
    OTHER_EQUITY_TOOL = Column(Float)
    OTHER_COMPRE_INCOME = Column(Float)
    SPECIAL_RESERVE = Column(Float)
    SURPLUS_RESERVE = Column(Float)
    UNASSIGN_RPOFIT = Column(Float)
    TOTAL_PARENT_EQUITY = Column(Float)
    MINORITY_EQUITY = Column(Float)
    OTHER_EQUITY_INVEST = Column(Float)
    TOTAL_EQUITY = Column(Float)
    TOTAL_LIAB_EQUITY = Column(Float)
    OPERATE_INCOME = Column(Float)
    INTEREST_INCOME = Column(Float)
    FEE_COMMISSION_INCOME = Column(Float)
    FE_INTEREST_INCOME = Column(Float)
    OTHER_INCOME = Column(Float)
    FAIRVALUE_CHANGE_INCOME = Column(Float)
    INVEST_INCOME = Column(Float)
    INVEST_JOINT_INCOME = Column(Float)
    ASSET_DISPOSAL_INCOME = Column(Float)
    NONBUSINESS_INCOME = Column(Float)
    OTHER_INCOME = Column(Float)
    TOTAL_OPERATE_INCOME = Column(Float)
    OPERATE_COST = Column(Float)
    INTEREST_EXPENSE = Column(Float)
    FEE_COMMISSION_EXPENSE = Column(Float)
    RESEARCH_EXPENSE = Column(Float)
    OPERATE_TAX_ADD = Column(Float)
    SALE_EXPENSE = Column(Float)
    MANAGE_EXPENSE = Column(Float)
    FINANCE_EXPENSE = Column(Float)
    ASSET_IMPAIRMENT_INCOME = Column(Float)
    CREDIT_IMPAIRMENT_INCOME = Column(Float)
    NONBUSINESS_EXPENSE = Column(Float)
    FE_INTEREST_EXPENSE = Column(Float)
    TOTAL_OPERATE_COST = Column(Float)
    OPERATE_PROFIT = Column(Float)
    TOTAL_PROFIT = Column(Float)
    INCOME_TAX = Column(Float)
    NETPROFIT = Column(Float)
    CONTINUED_NETPROFIT = Column(Float)
    PARENT_NETPROFIT = Column(Float)
    MINORITY_INTEREST = Column(Float)
    DEDUCT_PARENT_NETPROFIT = Column(Float)
    BASIC_EPS = Column(Float)
    DILUTED_EPS = Column(Float)
    PARENT_OCI = Column(Float)
    MINORITY_OCI = Column(Float)
    TOTAL_COMPRE_INCOME = Column(Float)
    PARENT_TCI = Column(Float)
    MINORITY_TCI = Column(Float)
    SALES_SERVICES = Column(Float)
    RECEIVE_TAX_REFUND = Column(Float)
    RECEIVE_OTHER_OPERATE = Column(Float)
    TOTAL_OPERATE_INFLOW = Column(Float)
    BUY_SERVICES = Column(Float)
    PAY_STAFF_CASH = Column(Float)
    PAY_ALL_TAX = Column(Float)
    PAY_OTHER_OPERATE = Column(Float)
    TOTAL_OPERATE_OUTFLOW = Column(Float)
    NETCASH_OPERATE = Column(Float)
    WITHDRAW_INVEST = Column(Float)
    RECEIVE_INVEST_INCOME = Column(Float)
    DISPOSAL_LONG_ASSET = Column(Float)
    DISPOSAL_SUBSIDIARY_OTHER = Column(Float)
    RECEIVE_OTHER_INVEST = Column(Float)
    TOTAL_INVEST_INFLOW = Column(Float)
    CONSTRUCT_LONG_ASSET = Column(Float)
    INVEST_PAY_CASH = Column(Float)
    OBTAIN_SUBSIDIARY_OTHER = Column(Float)
    INVEST_NETCASH_OTHER = Column(Float)
    TOTAL_INVEST_OUTFLOW = Column(Float)
    NETCASH_INVEST = Column(Float)
    ACCEPT_INVEST_CASH = Column(Float)
    SUBSIDIARY_ACCEPT_INVEST = Column(Float)
    RECEIVE_LOAN_CASH = Column(Float)
    FINANCE_NETCASH_OTHER = Column(Float)
    TOTAL_FINANCE_INFLOW = Column(Float)
    PAY_DEBT_CASH = Column(Float)
    ASSIGN_DIVIDEND_PORFIT = Column(Float)
    SUBSIDIARY_ACCEPT_INVEST = Column(Float)
    PAY_OTHER_FINANCE = Column(Float)
    FINANCE_OUTFLOW_OTHER = Column(Float)
    TOTAL_FINANCE_OUTFLOW = Column(Float)
    NETCASH_FINANCE = Column(Float)
    RATE_CHANGE_EFFECT = Column(Float)
    CCE_ADD = Column(Float)
    BEGIN_CCE = Column(Float)
    END_CCE = Column(Float)
    NETPROFIT = Column(Float)
    ASSET_IMPAIRMENT = Column(Float)
    FA_IR_DEPR = Column(Float)
    OILGAS_BIOLOGY_DEPR = Column(Float)
    IA_AMORTIZE = Column(Float)
    LPE_AMORTIZE = Column(Float)
    DISPOSAL_LONGASSET_LOSS = Column(Float)
    FIXED_ASSET_DISPOSAL = Column(Float)
    FAIRVALUE_CHANGE_LOSS = Column(Float)
    INVEST_LOSS = Column(Float)
    DEFER_TAX = Column(Float)
    DT_ASSET_REDUCE = Column(Float)
    DT_LIAB_ADD = Column(Float)
    INVENTORY_REDUCE = Column(Float)
    OPERATE_RECE_REDUCE = Column(Float)
    OPERATE_PAYABLE_ADD = Column(Float)
    OPERATE_NETCASH_OTHERNOTE = Column(Float)
    NETCASH_OPERATE = Column(Float)
    END_CASH = Column(Float)
    BEGIN_CASH = Column(Float)
    END_CASH_EQUIVALENTS = Column(Float)
    BEGIN_CCE = Column(Float)
    CCE_ADD = Column(Float)
    
    # 定义复合主键
    __table_args__ = (
        PrimaryKeyConstraint('SECURITY_CODE', 'REPORT_DATE', name='finance_statements_pk'),
    )
    